# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeagleChat' do
use_frameworks!

pod 'Beagle'
pod 'YogaKit', :git => 'https://github.com/lucasaraujo/yoga.git'

end