name: BeagleChat Android Pull Request

on:
  push:
    branches:
      - master
  pull_request:
        paths:
            - 'android/**'

jobs:
  test:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./android/Beagle-Chat/gradlew
    - name: Cache gradle dependences
      uses: actions/cache@v2
      env:
          gradle-cache-key: gradle-cache
          gradle-path: ~/.gradle
      with:
          path: ${{ env.gradle-path }}
          key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('android/Beagle-Chat/buildSrc/**') }}
    - name: Build with Gradle
      run: ./android/Beagle-Chat/gradlew build
    - name: Unit tests
      run: ./android/Beagle-Chat/gradlew test
