name: BeagleChat Android Pull Request

on:
  push:
    branches:
      - master
  pull_request:
        paths:
            - 'android/**'

jobs:
  test:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache gradle dependences
      uses: actions/cache@v2
      env:
          gradle-cache-key: gradle-cache
          gradle-path: ~/.gradle
      with:
          path: ${{ env.gradle-path }}
          key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('android/Beagle-Chat/buildSrc/**') }}
    - name: Run Kotlin Linter
      run: ./gradlew ktlintStagingDebugCheck
    - name: Run Android Linter
      run: ./android/Beagle-Chat/gradlew lintStagingDebug
    - name: Unit tests
      run: ./android/Beagle-Chat/gradlew test --stacktrace
    - name: Assemble Debug APK
      run: ./android/Beagle-Chat/gradlew assembleStagingDebug
